### ISSUE TITLE
No Response when Querying MDNS Cast Devices

### ISSUE THREAD

**Issue by d8ahazard** [clue/php-mdns-react#8]
Hello,

I'm trying to implement your MDNS library in a project I have that aims to communicate with chromecast devices.  

I'm trying to get results for the record _googlecast._tcp.local, but keep getiting a TimeoutException:

```
  Thu, 18 May 2017 14:37:32 -0500 [ DEBUG ] api.php::testReact - Function fired!
  Thu, 18 May 2017 14:37:37 -0500 [ ERROR ] api.php::{closure} - Error: 
  React\Dns\Query\TimeoutException: DNS query for _googlecast._tcp.local timed out in 
  /volume1/Webroot/Phlex/vendor/clue/mdns-react/src/MulticastExecutor.php:84
  Stack trace:
  #0 [internal function]: Clue\React\Mdns\MulticastExecutor->Clue\React\Mdns\{closure}
  (Object(React\EventLoop\Timer\Timer))
  #1 /volume1/Webroot/Phlex/vendor/react/event-loop/src/Timer/Timers.php(90): 
  call_user_func(Object(Closure), Object(React\EventLoop\Timer\Timer))
  #2 /volume1/Webroot/Phlex/vendor/react/event-loop/src/StreamSelectLoop.php(177): 
  React\EventLoop\Timer\Timers->tick()
  #3 /volume1/Webroot/Phlex/api.php(1857): React\EventLoop\StreamSelectLoop->run()
  #4 /volume1/Webroot/Phlex/api.php(1732): testReact()
  #5 /volume1/Webroot/Phlex/api.php(164): scanDevices()
  #6 {main}
```
I don't see any other glaring errors in my logs that would indicate a systemic error, but I could also be mistaken.  

I'm invoking the lookup like so:

```
  function testReact() {
   write_log("Function fired!");
      $name = '_googlecast._tcp.local';
      $loop = React\EventLoop\Factory::create();
      $factory = new Clue\React\Mdns\Factory($loop);
      $mdns = $factory->createResolver();
      $mdns->resolve($name)->then(function ($value) {
          write_log("Value: ".$value);
      },function ($value) {
          write_log("Error: ".$value,"ERROR");
      });
      $loop->run();
  }
```

I'm running this on Synology with apache 2.4 and php7.  

Thanks!

**Comment by clue** [comment]
Thanks for your interesting question!

It looks like what you're trying to achieve is actually DNS-SD instead of mDNS, as mentioned in the readme:

> This library implements the mDNS protocol as defined in RFC 6762. Note that this protocol is related to, but independent of, DNS-Based Service Discovery (DNS-SD) as defined in RFC 6763.

In other words: mDNS deals with finding the IP of a given hostname via multicast, while DNS-SD can be used to find a list of devices that offer a certain service.

I hope this helps :+1:
